In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

1.13.1


### Introduction to Tensors

In [3]:
# Scalar (0D tensor)
scalar = torch.tensor(3.1415)
print(scalar)

tensor(3.1415)


In [10]:
# Vector (1D tensor)
vector = torch.tensor([1, 2, 3, 4, 5])
print(vector)

tensor([1, 2, 3, 4, 5])


In [18]:
other_vector = torch.arange(1, 6)
print(other_vector)
print(vector == other_vector, vector.shape)

tensor([1, 2, 3, 4, 5])
tensor([True, True, True, True, True]) torch.Size([5])


In [27]:
# Matrix
matrix = torch.tensor([[1, 2], [4, 5]])

print(matrix)

tensor([[1, 2],
        [4, 5]])


In [33]:
TENSOR = torch.tensor([[[1, -1, 0],
                        [2, 0, 1],
                          [4, 1, 0],
                            [6, 0, 1]]])
print(TENSOR)

tensor([[[ 1, -1,  0],
         [ 2,  0,  1],
         [ 4,  1,  0],
         [ 6,  0,  1]]])


In [34]:
TENSOR.shape

torch.Size([1, 4, 3])

In [35]:
TENSOR.ndim

3

### Random Tensors

Why do we need random tensors? Random tensors are useful for initializing the weights of neural networks. We will learn more about this in the next lesson.

In [42]:
# Random tensors
random_tensor = torch.rand(3, 4, 5)
print(random_tensor)

tensor([[[0.9545, 0.4976, 0.9336, 0.1765, 0.2997],
         [0.3670, 0.3845, 0.0935, 0.1126, 0.6940],
         [0.0465, 0.0367, 0.8529, 0.5588, 0.0148],
         [0.8884, 0.9097, 0.5475, 0.4254, 0.8654]],

        [[0.5163, 0.1426, 0.1004, 0.4389, 0.1185],
         [0.9222, 0.9318, 0.1760, 0.3467, 0.3947],
         [0.7754, 0.7576, 0.1391, 0.5181, 0.2161],
         [0.8226, 0.0193, 0.0674, 0.6016, 0.1217]],

        [[0.9507, 0.0025, 0.9830, 0.9472, 0.8941],
         [0.5252, 0.7507, 0.4825, 0.6466, 0.1163],
         [0.3574, 0.6522, 0.0891, 0.8660, 0.0504],
         [0.3442, 0.1452, 0.0024, 0.5404, 0.5459]]])


In [52]:
other_random_tensor = torch.randn(3, 4, 7)
print(other_random_tensor)

tensor([[[-2.3710, -0.8751,  0.0693,  1.5853, -1.1846,  0.1068, -0.6729],
         [ 1.4875, -0.0743,  1.1090,  1.2451,  0.1415,  1.1672,  0.1820],
         [-1.2224,  0.9455, -1.0133,  0.3462, -0.1871,  0.7392,  0.5829],
         [-2.8387,  0.5218, -0.6013, -0.6262,  1.3650, -0.8247,  0.7255]],

        [[-0.4978,  0.2873,  0.1436, -0.2023, -0.7466,  0.0592,  0.9684],
         [ 1.6999,  0.8969,  0.7516, -0.0576,  1.7022,  0.1361,  0.5812],
         [ 0.0047, -1.3984, -0.6336, -0.6668,  1.5470,  2.1056,  0.4774],
         [ 0.5965,  1.4588,  0.7178,  0.0241, -1.6986,  0.7098,  1.5676]],

        [[ 0.1447,  1.8930,  1.9312,  0.8216,  0.1941, -0.4811,  1.6345],
         [ 0.2891, -0.5341, -0.5915, -2.2003, -0.0482, -0.4796,  1.0995],
         [ 0.3376, -0.7319,  1.5728,  2.1317,  0.6963, -1.5608, -2.9887],
         [-0.5780, -0.2286, -0.5004,  1.0900,  0.4223, -0.8505,  0.7542]]])


In [54]:
other_random_tensor.ndim

3

In [56]:
# Permuted dimensions
permuted_tensor = other_random_tensor.permute(2, 0, 1)
print(permuted_tensor)

tensor([[[-2.3710,  1.4875, -1.2224, -2.8387],
         [-0.4978,  1.6999,  0.0047,  0.5965],
         [ 0.1447,  0.2891,  0.3376, -0.5780]],

        [[-0.8751, -0.0743,  0.9455,  0.5218],
         [ 0.2873,  0.8969, -1.3984,  1.4588],
         [ 1.8930, -0.5341, -0.7319, -0.2286]],

        [[ 0.0693,  1.1090, -1.0133, -0.6013],
         [ 0.1436,  0.7516, -0.6336,  0.7178],
         [ 1.9312, -0.5915,  1.5728, -0.5004]],

        [[ 1.5853,  1.2451,  0.3462, -0.6262],
         [-0.2023, -0.0576, -0.6668,  0.0241],
         [ 0.8216, -2.2003,  2.1317,  1.0900]],

        [[-1.1846,  0.1415, -0.1871,  1.3650],
         [-0.7466,  1.7022,  1.5470, -1.6986],
         [ 0.1941, -0.0482,  0.6963,  0.4223]],

        [[ 0.1068,  1.1672,  0.7392, -0.8247],
         [ 0.0592,  0.1361,  2.1056,  0.7098],
         [-0.4811, -0.4796, -1.5608, -0.8505]],

        [[-0.6729,  0.1820,  0.5829,  0.7255],
         [ 0.9684,  0.5812,  0.4774,  1.5676],
         [ 1.6345,  1.0995, -2.9887,  0.7542]]])

In [57]:
permuted_tensor.shape

torch.Size([7, 3, 4])

In [58]:
# Select elements from tensor
print(permuted_tensor[:, 0, 0])

tensor([-2.3710, -0.8751,  0.0693,  1.5853, -1.1846,  0.1068, -0.6729])
